spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    properties:
      hibernate:
        default_schema: webguide

logging:
  level:
    p6spy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.jdbc.core: TRACE
    # 패키지 전체
    com.webguide.search.service: DEBUG
    org.springframework.context: DEBUG
    org.springframework.boot.context.properties: DEBUG